import { useState } from 'react';
import { download, type Workspace } from './workspace';
const titles:Record<string,string>={'project.validate':'Validación del proyecto','project.edit-plan':'Instrucciones de edición'};
const states:Record<string,string>={queued:'En cola',running:'En ejecución',completed:'Completado',failed:'Fallido',cancelled:'Cancelado'};
export function Activity({workspace:w}:{workspace:Workspace}){
  const [all,setAll]=useState(false),[output,setOutput]=useState('');const jobs=w.jobs.filter(j=>all||j.projectId===w.project?.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  return <div className="content"><section className="hero compact glass"><div><p className="eyebrow">TRABAJOS Y RECUPERACIÓN</p><h2>Activity</h2><p>Resultados ligados a la revisión que los creó. Al reabrir la app, los trabajos interrumpidos quedan disponibles para reintentar.</p></div></section>
    <section className="glass card"><div className="section-head"><h3>{all?'Todos los proyectos':w.project?.content.name||'Selecciona un proyecto'}</h3><label className="toggle"><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/> Ver todos</label></div><div className="actions"><button disabled={!w.project||w.busy} onClick={()=>void w.enqueue('project.validate')}>Validar estructura</button><button disabled={!w.project||w.busy} onClick={()=>void w.enqueue('project.edit-plan')}>Crear instrucciones TXT</button></div>
      {!jobs.length?<div className="empty dashed">Todavía no hay trabajos. Puedes validar tu plan o generar sus instrucciones.</div>:<div className="jobs">{jobs.map(j=><article className="job" key={j.id}><div className="section-head"><div><strong>{titles[j.kind]||j.kind}</strong><small>{j.input.name} · revisión {j.sourceRevision} · intento {j.attempt}/{j.maxAttempts}</small></div><span className={`pill ${j.status}`}>{states[j.status]}</span></div><progress max={1} value={j.progress}/><div className="job-detail"><span>{Math.round(j.progress*100)}%</span><small>{new Date(j.updatedAt).toLocaleString()}</small></div>{j.error&&<p className="job-error">{j.error}</p>}<div className="actions">{['queued','running'].includes(j.status)&&<button disabled={w.busy} onClick={()=>void w.jobAction(j.id,'cancel')}>Cancelar</button>}{['failed','cancelled'].includes(j.status)&&<button disabled={w.busy||j.attempt>=j.maxAttempts} onClick={()=>void w.jobAction(j.id,'retry')}>Reintentar</button>}{j.output!==undefined&&<><button onClick={()=>setOutput(j.output!)}>Ver resultado</button><button onClick={()=>download(`abraxas-${j.id}.${j.kind==='project.validate'?'json':'txt'}`,j.output!,j.kind==='project.validate'?'application/json':'text/plain')}>Descargar</button></>}</div></article>)}</div>}
    </section>{output&&<section className="glass card"><div className="section-head"><h3>Resultado</h3><button onClick={()=>setOutput('')}>Cerrar</button></div><pre>{output}</pre></section>}
  </div>;
}
