import { useState, type FormEvent } from 'react';
import { graphSchema, type ProductionEvent } from '@abraxas/contracts';
import { download, type Workspace } from './workspace';

export const labels:Record<string,string>={a_roll:'A-roll',b_roll:'B-roll',xr:'X-roll',image:'Imagen',motion:'Motion',caption:'Subtítulos',sfx:'SFX',music:'Música',vo:'Voz',transition:'Transición',note:'Nota'};
const statusLabels:Record<string,string>={ghost:'Propuesta',planned:'Planificado',creating:'En creación',ready:'Listo',review:'Por revisión',approved:'Aprobado',failed:'Fallido'};
export function ProjectHub({workspace:w}:{workspace:Workspace}){
  const [name,setName]=useState(''),[fps,setFps]=useState('30/1');
  const p=w.project;
  const create=(e:FormEvent)=>{e.preventDefault();const [fpsNumerator,fpsDenominator]=fps.split('/').map(Number);void w.create(name,{fpsNumerator,fpsDenominator});};
  return <div className="content">
    <section className="hero glass"><div><p className="eyebrow">TU ESTUDIO DE PRODUCCIÓN</p><h2>El proyecto empieza aquí.</h2><p>Organiza decisiones, recursos y trabajos en un mismo lugar. Esta entrega pone en marcha la base de tus próximos videos.</p></div><span className="pill real">Foundation 01 · funcional</span></section>
    <div className="grid two">
      <section className="glass card"><h3>Crear proyecto</h3><form onSubmit={create} className="form-stack"><label>Nombre<input value={name} onChange={e=>setName(e.target.value)} placeholder="JOC · Podcast Amanda" required maxLength={160}/></label><label>Fotogramas por segundo<select value={fps} onChange={e=>setFps(e.target.value)}>{['24/1','25/1','30/1','30000/1001','60/1','60000/1001'].map(value=><option key={value} value={value}>{value.includes('1001')?value==='30000/1001'?'29.97':'59.94':value.split('/')[0]} fps</option>)}</select></label><button className="primary" disabled={w.busy||!w.connected||!name.trim()}>Crear y abrir</button></form></section>
      <section className="glass card"><div className="section-head"><h3>Mis proyectos</h3><span>{w.projects.length}</span></div>{!w.projects.length?<p className="empty">Crea tu primer proyecto. Puedes cerrar la app y continuar después.</p>:<div className="project-list">{w.projects.map(project=><button key={project.id} disabled={w.busy} className={p?.id===project.id?'selected':''} onClick={()=>void w.select(project.id)}><strong>{project.content.name}</strong><small>{project.content.graph.events.length} eventos · revisión {project.revision}</small></button>)}</div>}</section>
    </div>
    {p&&<ProjectEditor key={p.id} workspace={w}/>}
  </div>;
}
function ProjectEditor({workspace:w}:{workspace:Workspace}){
  const p=w.project!;const [editing,setEditing]=useState<ProductionEvent|null>(null),[adding,setAdding]=useState(false),[importGraph,setImportGraph]=useState<ReturnType<typeof graphSchema.parse>|null>(null);
  const graph=p.content.graph;const maxFrame=Math.max(1,...graph.events.map(e=>e.endFrame));const fps=graph.timebase.fpsNumerator/graph.timebase.fpsDenominator;
  const updateName=(e:FormEvent)=>{e.preventDefault();const name=String(new FormData(e.currentTarget as HTMLFormElement).get('name'));void w.save({...p.content,name},'Cambiar nombre');};
  const saveEvent=async(event:ProductionEvent)=>{const exists=graph.events.some(e=>e.id===event.id);const saved=await w.save({...p.content,graph:{...graph,events:exists?graph.events.map(e=>e.id===event.id?event:e):[...graph.events,event]}},`${exists?'Editar':'Añadir'} ${labels[event.kind]}`);if(saved){setEditing(null);setAdding(false);}};
  return <>
    <section className="glass card editor"><div className="section-head"><div><p className="eyebrow">PROYECTO ABIERTO</p><h3>{p.content.name}</h3></div><div className="actions"><button disabled={w.busy||!p.history.undo.length} onClick={()=>void w.travel('undo')}>↶ Deshacer</button><button disabled={w.busy||!p.history.redo.length} onClick={()=>void w.travel('redo')}>↷ Rehacer</button></div></div>
      <div className="metrics"><div><strong>{graph.events.length}</strong><small>Eventos</small></div><div><strong>{(maxFrame===1&&!graph.events.length?0:maxFrame/fps).toFixed(2)} s</strong><small>Extensión del plan</small></div><div><strong>{fps.toFixed(fps%1?2:0)}</strong><small>FPS · {graph.timebase.fpsNumerator}/{graph.timebase.fpsDenominator}</small></div><div><strong>r{p.revision}</strong><small>Guardada {new Date(p.updatedAt).toLocaleTimeString()}</small></div></div>
      <form onSubmit={updateName} className="inline-form"><label className="sr-only" htmlFor="project-name">Renombrar proyecto</label><input id="project-name" name="name" key={p.content.name} defaultValue={p.content.name} required maxLength={160}/><button disabled={w.busy}>Guardar nombre</button></form>
      <div className="section-head"><h3>Plan por fotogramas</h3><button className="primary" disabled={w.busy} onClick={()=>{setEditing(null);setAdding(true);}}>+ Añadir evento</button></div>
      <p className="muted">Cada rango incluye el inicio y excluye el final. El plan todavía no reproduce ni renderiza video.</p>
      {!graph.events.length?<div className="empty dashed">Añade tu primer A-roll, B-roll, X-roll o nota para construir el plan.</div>:<>
        <div className="timeline" aria-label="Vista del plan por eventos">{[...graph.events].sort((a,b)=>a.startFrame-b.startFrame).map(event=><div className="timeline-row" key={event.id}><span>{labels[event.kind]}</span><div className="timeline-track"><button aria-label={`Editar ${event.id}`} className={`event-bar ${event.kind}`} style={{left:`${event.startFrame/maxFrame*100}%`,width:`${Math.max(1,(event.endFrame-event.startFrame)/maxFrame*100)}%`}} onClick={()=>{setAdding(false);setEditing(event);}} title={`${event.id}: ${event.startFrame}–${event.endFrame}`}>{event.label||labels[event.kind]}</button></div></div>)}</div>
        <div className="table-scroll"><table><thead><tr><th>Evento</th><th>Tipo</th><th>Inicio</th><th>Final</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{[...graph.events].sort((a,b)=>a.startFrame-b.startFrame).map(e=><tr key={e.id}><td title={e.id}>{e.label||labels[e.kind]}</td><td><span className={`kind-dot ${e.kind}`}/>{labels[e.kind]}</td><td>{e.startFrame} f</td><td>{e.endFrame} f</td><td>{statusLabels[e.status]}</td><td className="actions"><button disabled={w.busy} onClick={()=>{setAdding(false);setEditing(e);}}>Editar</button><button disabled={w.busy} onClick={()=>void w.save({...p.content,graph:{...graph,events:graph.events.filter(x=>x.id!==e.id)}},`Quitar ${e.id}`)}>Quitar</button></td></tr>)}</tbody></table></div>
      </>}
      {(editing||adding)&&<EventForm key={editing?.id||'new'} event={editing} busy={w.busy} onSave={saveEvent} onClose={()=>{setEditing(null);setAdding(false);}}/>}
      <div className="actions separated"><button disabled={w.busy} onClick={()=>void w.enqueue('project.validate')}>Validar estructura</button><button disabled={w.busy} onClick={()=>void w.enqueue('project.edit-plan')}>Crear instrucciones TXT</button><button onClick={()=>download(`abraxas-${p.id}-graph.json`,JSON.stringify(graph,null,2))}>Descargar graph</button><label className="file-button">Importar graph<input type="file" accept=".json,application/json" disabled={w.busy} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>5_000_000)throw new Error('Límite de 5 MB.');setImportGraph(graphSchema.parse(JSON.parse(await file.text())));}catch(error){w.setError(error instanceof Error?error.message:'Graph inválido.');}}}/></label></div>
      {importGraph&&<div className="import-preview"><h4>Importar {importGraph.events.length} eventos</h4><p>Sustituirá el plan abierto y su FPS. Puedes deshacerlo después. Los recursos son referencias; no se importan archivos de video.</p><div className="actions"><button disabled={w.busy} onClick={()=>{void w.save({...p.content,graph:{...importGraph,projectId:p.id}},'Importar Production Graph');setImportGraph(null);}}>Aplicar al proyecto</button><button onClick={()=>setImportGraph(null)}>Cancelar</button></div></div>}
    </section>
    <section className="glass card"><h3>Historial persistente</h3>{!p.history.undo.length?<p className="muted">Las próximas ediciones aparecerán aquí.</p>:<ol className="history-list">{[...p.history.undo].reverse().slice(0,8).map(o=><li key={o.id}><span>{o.label}</span><small>{new Date(o.timestamp).toLocaleString()}</small></li>)}</ol>}</section>
  </>;
}
function EventForm({event,busy,onSave,onClose}:{event:ProductionEvent|null;busy:boolean;onSave:(e:ProductionEvent)=>Promise<void>;onClose:()=>void}){
  const [kind,setKind]=useState(event?.kind||'b_roll'),[start,setStart]=useState(event?.startFrame||0),[end,setEnd]=useState(event?.endFrame||90),[status,setStatus]=useState(event?.status||'planned'),[refs,setRefs]=useState(event?.assetRefs?.join(', ')||''),[label,setLabel]=useState(event?.label||''),[error,setError]=useState('');
  return <form className="event-form" onSubmit={e=>{e.preventDefault();const result=graphSchema.safeParse({schemaVersion:'abraxas.production-graph.v2',projectId:'validation',timebase:{fpsNumerator:30,fpsDenominator:1},events:[{...event,id:event?.id||crypto.randomUUID(),kind,label:label.trim()||labels[kind],startFrame:start,endFrame:end,status,assetRefs:refs.split(',').map(x=>x.trim()).filter(Boolean)}]});if(!result.success){setError(result.error.issues.map(i=>i.message).join(' '));return;}onSave(result.data.events[0]);}}>
    <div className="section-head"><h4>{event?'Editar evento':'Nuevo evento'}</h4><button type="button" onClick={onClose}>Cerrar</button></div>
    <label>Nombre del evento<input value={label} onChange={e=>setLabel(e.target.value)} maxLength={160} placeholder={labels[kind]}/></label><div className="form-grid"><label>Tipo<select value={kind} onChange={e=>setKind(e.target.value as ProductionEvent['kind'])}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Inicio (frames)<input type="number" min={0} step={1} value={start} onChange={e=>setStart(Number(e.target.value))} required/></label><label>Final exclusivo (frames)<input type="number" min={1} step={1} value={end} onChange={e=>setEnd(Number(e.target.value))} required/></label><label>Estado<select value={status} onChange={e=>setStatus(e.target.value as ProductionEvent['status'])}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div>
    <label>IDs de recursos (separados por coma)<input value={refs} onChange={e=>setRefs(e.target.value)} placeholder="master-01, foto-clinica-02"/></label>{error&&<p role="alert">{error}</p>}<button className="primary" disabled={busy}>Guardar evento</button>
  </form>;
}
